# Generated by Django 4.2.3 on 2023-07-27 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shutafim', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='entry_date',
            field=models.DateField(),
        ),
    ]
