# Generated by Django 4.2.3 on 2023-07-27 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shutafim', '0003_alter_apartment_entry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='details',
            field=models.CharField(default='', max_length=400),
        ),
    ]
