# Generated by Django 4.2.3 on 2023-07-27 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shutafim', '0004_apartment_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='details',
            field=models.CharField(default='', max_length=500),
        ),
    ]
