# Generated by Django 4.2.3 on 2023-07-27 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shutafim', '0005_apartment_title_alter_apartment_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagedata',
            old_name='url',
            new_name='myurl',
        ),
    ]
