# Generated by Django 4.2.3 on 2023-08-03 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shutafim', '0008_apartment_agree_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='type',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='imagedata',
            name='internal',
            field=models.BooleanField(default=True),
        ),
    ]
