# Generated by Django 3.2.20 on 2023-08-13 11:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shutafim', '0009_apartment_type_imagedata_internal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateField(default=django.utils.timezone.now)),
                ('mes_content', models.CharField(max_length=500)),
                ('mes_from', models.CharField(max_length=100)),
                ('mes_contact', models.CharField(max_length=100)),
                ('mes_read', models.BooleanField(default=False)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shutafim.apartment')),
            ],
        ),
    ]
