# Generated by Django 3.2.20 on 2023-08-13 11:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shutafim', '0010_messages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='apartment',
        ),
        migrations.AddField(
            model_name='messages',
            name='user_to',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
