# Generated by Django 3.2.20 on 2023-08-13 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shutafim', '0011_auto_20230813_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='apartment',
            field=models.ForeignKey(default=13, on_delete=django.db.models.deletion.CASCADE, to='shutafim.apartment'),
            preserve_default=False,
        ),
    ]
