# Generated by Django 3.2.20 on 2023-08-13 17:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shutafim', '0012_messages_apartment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='datetime',
            field=models.DateField(default=datetime.datetime(2023, 8, 13, 17, 39, 43, 329123, tzinfo=utc)),
        ),
    ]
