# Generated by Django 3.2.20 on 2023-08-13 17:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shutafim', '0013_alter_messages_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='datetime',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
