# Generated by Django 3.2.20 on 2023-08-13 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shutafim', '0014_alter_messages_datetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='datetime',
            new_name='pub_date',
        ),
    ]
