# Generated by Django 3.2.20 on 2023-08-15 20:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shutafim', '0017_alter_messages_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='update',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
