# Generated by Django 3.2.20 on 2023-08-16 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shutafim', '0018_apartment_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='mes_content',
            field=models.CharField(max_length=650),
        ),
    ]
