# Generated by Django 3.2.20 on 2023-08-16 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shutafim', '0020_apartment_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='link',
        ),
        migrations.AlterField(
            model_name='messages',
            name='mes_content',
            field=models.CharField(max_length=500),
        ),
    ]
